//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8825
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentInformation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StudentInformation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Icon backpack {
            get {
                object obj = ResourceManager.GetObject("backpack", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.IO.UnmanagedMemoryStream beautiful_people {
            get {
                return ResourceManager.GetStream("beautiful_people", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream bell {
            get {
                return ResourceManager.GetStream("bell", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream bollon {
            get {
                return ResourceManager.GetStream("bollon", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream bonn {
            get {
                return ResourceManager.GetStream("bonn", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream cash1 {
            get {
                return ResourceManager.GetStream("cash1", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream delete {
            get {
                return ResourceManager.GetStream("delete", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream don {
            get {
                return ResourceManager.GetStream("don", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream gaincoil {
            get {
                return ResourceManager.GetStream("gaincoil", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream happy_kd {
            get {
                return ResourceManager.GetStream("happy_kd", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream pox {
            get {
                return ResourceManager.GetStream("pox", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream poxpoxpox {
            get {
                return ResourceManager.GetStream("poxpoxpox", resourceCulture);
            }
        }
        
        public static System.IO.UnmanagedMemoryStream techni {
            get {
                return ResourceManager.GetStream("techni", resourceCulture);
            }
        }
    }
}
